config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :owners
  get 'dashboard' => 'clubs#index'
  get 'privacy' => 'pages#privacy'

  root to: 'pages#home'

  resources :clubs do
    resources :photos, only: [:create]
  end

  resources :events, :tables
  resources :bookings, only: [:create, :new, :destroy]

  get 'bookings/new/:club_id/:event_id/:table_id', to: "bookings#new", as: "facebook"

end

app/models/club.rb
class Club < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true
  belongs_to :owner
  has_many :events

  has_many :photos
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

  before_action :club, only: [:show, :edit, :destroy, :update]

  def index
    if current_owner
      @clubs = current_owner.clubs
    else
      if params[:city] == ""
        params[:city] == "Las Vegas"
      end
      @clubs = Club.where(city: params[:city])
    end
  end

  def new
    @club = Club.new
  end
  def create
    @club = Club.new(club_params)
    if @club.save
      @club.photos.create(
        photo:       params[:club][:photo][:photo],
        photo_cache: params[:club][:photo][:photo_cache]
      )
      redirect_to club_path(@club)
    else
      render :new
    end
  end

  def show
    @events = Event.all
  end

  def edit
  end

  def update
    @club.update_attributes(club_params)
    if @club.save
      @club.photos.create(
        photo:       params[:club][:photo][:photo],
        photo_cache: params[:club][:photo][:photo_cache]
      )
      redirect_to club_path(@club)
    else
      render :new
    end
  end


  private

  def club
    @club = Club.find(params[:id])
  end

  def club_params
    params.require(:club).permit(:name, :address, :city, :description,
     :owner_id, :photo, :photo_cache)
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_edit.html.erb
<!-- <div class="container">
<h1 class="text-center">Edit Club</h1>

<%= simple_form_for @club do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :description %>

    <%= f.button :submit %>
  <% end %>

<br>
<h3>Add Another Photo </h3>
<%= simple_form_for [@club, Photo.new] do |p| %>
      <%= p.input :photo %>
      <%= p.input :photo_cache, as: :hidden %>
      <%= p.button :submit %>
    <% end %>
</div>
 -->

app/views/clubs/edit.html.erb
<div class="container">
<h1 class="text-center">Edit Club</h1>

<%= render '/shared/club' %>

</div>

app/views/clubs/index.html.erb
<!-- clubs index page-->
<div class="container">
  <div class="row">
  <h1> Clubs </h1>
   <% @clubs.each do |club| %>
   <div class="col-xs-12 col-md-4">
    <%= link_to club_path(club) do %>
    <div class="card small card-product hoverable">
      <div class='card-thumbnail' style="background-image: url('<%= image_url club.photos.first.try(:photo) %>');" >
      </div>
      <div class="card-category"><%= club.name %></div>
      <div class="card-description"> <%= club.city %> </div>
    </div>
    <% end %>
  </div>
  <% end %>
</div>
</div>

app/views/clubs/new.html.erb
<div class="container">
  <h1 class="text-center">New Club</h1>

  <%= render '/shared/club' %>

</div>

app/views/clubs/show.html.erb
<!--club's page -->
<div class="container">
  <div class="row text-center">
    <div class="col-xs-12" style="padding: 40px 0;">
      <h2><span class="Roboto-Bold"> Club <%= @club.name %> - <%= @club.description %></span>
        <h3><span class="Roboto-Bold"style="opacity: .3;"><%= @club.address %>, <%= @club.city %></span>
        </div>
      </div>
    </div>


    <div class="container">
      <% @club.photos.each do |photo| %>
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          <%= cl_image_tag photo.photo, height: 300, crop: :fill, class: "fuckoff" %>
        </div>
        <% end %>
      </div>
      <%#= link_to "Events", events_path(club_id: @club.id), class:"btn btn-default" %>
    </div>
  </div>

  <div class="divider-new text-center">Upcoming events</div>


<div class="container">
  <div class="row">
    <% @events.each do |event| %>
    <% @club_id = event.club_id %>
    <% @club = Club.find(@club_id) %>
      <div class="col-xs-12 col-md-4">
        <%= link_to event_path(event) do %>

        <div class="card small card-product hoverable">

          <div class='card-thumbnail' style="background-image: url('<%= image_url event.photos.first.try(:photo) %>');" >
            <div class="card-thumbnail-price"><%="Tables starts at $ " + event.cheapest_table + " " %>
            </div>
          </div>

          <div class="events-data">
            <ul class="list-inline">
              <li><%= event.starts_at.strftime("%-d %b") %></li>
            </ul>
          </div>

          <div class="events-data-cta">
            <div class="description">
              <%= link_to "Book table and invite ppl", event_path(event), class: "join-button" %>
            </div>
          </div>



          <!-- <div class="row events-data">
            <div class="col-xs-12 col-md-4">
              <ul class="list-inline event-list">
                <li><%#= event.starts_at.strftime("%-d %b") %></li>
                <li><%#= @club.name %></li>
                <li><%#= @club.city %></li>
              </ul>
            </div>
            <!-- </div> -->
            <!-- <div class="row" -->
            <!-- <div class="col-xs-12 col-md-4">
              <div class="events-data-cta"> -->
                <%#= link_to "Book table and invite ppl", event_path(event), class: "join-button" %>
              <!-- </div>
            </div>
          </div>

        </div> -->

        </div>

        <% end %>
      </div>
    <% end %>
  </div>
</div>