config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :owners
  get 'dashboard' => 'clubs#index'
  get 'privacy' => 'pages#privacy'

  root to: 'pages#home'

  resources :clubs do
    resources :photos, only: [:create]
  end

  resources :events, :tables
  resources :bookings, only: [:create, :new, :destroy]

  get 'bookings/new/:club_id/:event_id/:table_id', to: "bookings#new", as: "facebook"

end

app/views/shared/_club.html.erb
<%= simple_form_for @club do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :description %>

    <%= f.simple_fields_for Photo.new do |p| %>
      <%= p.input :photo %>
      <%= p.input :photo_cache, as: :hidden %>
    <% end %>

    <%= f.button :submit %>

  <% end %>

app/views/shared/_event.html.erb
<div class="container text-center">
  <div class="row">

    <div class="col-xs-12 ">

      <h5> <%= @event.starts_at.strftime("%-d %b") %>  : <%= @event.description %>
       @ <%= @club.name %> - <%= @club.description %> </h5>
     </div>
   </div>
 </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer center-on-small-only">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">footer content.</p>
      </div>
      <div class="col-md-6">
        <h5 class="white-text">Links</h5>
        <ul>
          <% if current_owner.nil? %>
            <li><%= link_to t(".sign_in", default: "Owner Login"), new_owner_session_path %></li>
          <% else %>
            <li><%= link_to "Owner Logout", destroy_owner_session_path, method: :delete %></li>
          <% end %>
          <!-- <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li> -->
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright text-center rgba-black-light">
    <div class="container">
      © 2015 Copyright: <a href="#"> blablalink </a>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="nav-cool">
  <div class="dropdown nav-cool-menu">
    <a href="#" class="dropdown-toggle waves-effect waves-light" data-toggle="dropdown" role="button" aria-expanded="false">
      <i class='fa fa-bars'></i>
    </a>
    <ul class="dropdown-menu navbar-menu" role="menu">
      <% if current_user %>
        <li>
          <%= image_tag current_user.picture, class: "avatar large" %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
          <% end %>
        </li>
        <% else %>
          <li>
            <%= link_to t(".sign_in", default: "Login"), new_user_session_path%>
          </li>
        <% end %>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
          <% end %>
        </li>
    </ul>
  </div>
  <div class='nav-cool-logo'>
  <!-- Logo -->
  <%= link_to root_path, class: "nav-cool-logo" do %>
    <%= image_tag "pixxer_logo.png", height: 50, width: 100, crop: :fill %>
  <% end %>

  </div>
  <div class="nav-cool-right">
    <div class="nav-cool-right-item">
      Host
    </div>
    <span class='separator'>
    </span>
    <div class="nav-cool-right-item">
      Join
    </div>
  </div>
</div>