config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :owners
  get 'dashboard' => 'clubs#index'
  get 'privacy' => 'pages#privacy'

  root to: 'pages#home'

  resources :clubs do
    resources :photos, only: [:create]
  end

  resources :events, :tables
  resources :bookings, only: [:create, :new, :destroy]

  get 'bookings/new/:club_id/:event_id/:table_id', to: "bookings#new", as: "facebook"

end

app/views/pages/_table_card.html.erb
<!--Rotating card-->
<div class="card-wrapper">
  <div id="card-<%=index%>" class="card-rotating effect__click">
    <!--Front Side-->
    <div class="face card-rotating__front z-depth-1">
      <div class="card-up">
        <%= image_tag table.event.photos.first.try(:photo) %>
      </div>
      <div class="avatar">
        <%= image_tag table.user.picture %> class="img-circle img-responsive">
      </div>
        <br>
      <h7>Available seats: <%= table.available_seats %>
        <br>
        <br>
        Price to join: $ <%= table.per_seat %> </h7>
      <br>
      <br>
      <!--Triggering button-->
      <a class="rotate-btn" style="color: black;" data-card="card-<%=index%>"><!-- <i class="fa fa-repeat"> --> Meet the team<!-- </i> --></a>


      <div><%= link_to "Join this Table", new_booking_path(table, club_id: table.event.club.id, event_id: table.event.id, table_id: table.id), class: 'join-button' %>
      </div>
    </div>
    <!--/.Front Side-->

    <!--Back Side-->
    <div class="face card-rotating__back z-depth-1">
      <div class="text-left small">

        <% table.bookings.order(:id).each do |booking|  %>

          <div class="row team">
            <%= image_tag(booking.user.picture,  class: "avatar-large") %>
            <span class="mark">
              <%= booking.user.first_name %> <%=booking.user.last_name %>
            </span>
            <div class="teammember-details">
              Booked <%= booking.seats %> seats <br>
              Personal message: <%= booking.description %>
            </div>
          </div>
      <% end %>
      </div>


      <div><%= link_to "Join this Table", new_booking_path(table, club_id: table.event.club.id, event_id: table.event.id, table_id: table.id), class: 'join-button' %>
      </div>
        <!-- <br> Lorem ipsum</p>
        <hr> Lorem ipsum
        <br> Lorem ipsum
        <br> Lorem ipsum
        <br> Lorem ipsum
        <br> Lorem ipsum
        <br> Lorem ipsum
        <br> -->

    <!--Triggering button-->
      <a class="rotate-btn" style="color: black;" data-card="card-<%=index%>">
        Go Back <i class="fa fa-undo"></i>
      </a>
      <h6>This table has <%= table.available_seats %> available seats out of <%= table.seats %> seats</h6>
      <div class="sm-container">
        <ul class="list-inline card-sm">
          <li><a class="icons-sm fb-ic"><i class="fa fa-facebook"></i></a></li>
          <li><a class="icons-sm tw-ic"><i class="fa fa-twitter"></i></a></li>
          <li><a class="icons-sm gplus-ic"><i class="fa fa-google-plus"></i></a></li>
          <li><a class="icons-sm li-ic"><i class="fa fa-linkedin"></i></a></li>
        </ul>
      </div>
    </div>
    <!--/.Back Side-->
  <!--/.Rotating card-->
  </div>
</div>

app/views/pages/home.html.erb
 <!-- Section: Intro -->
    <!-- <section id="intro" class="full-bg-img">
        <div class="container">
            <div class="verticalcenter text-center white-text">
              <h3>Some awesome heading</h3> -->
              <!--Call to action buttons-->
                <!-- <a href="#" class="btn btn-primary waves-effect waves-light">Contact me</a>
                <a href="#" class="btn btn-primary waves-effect waves-light">Learn more</a> -->
          <!--   </div>
        </div>
    </section> -->
    <!--/. Section: Intro -->


<div class="mask rgba-black-light">
  <div class="banner">
    <div class="banner-content text-center">
      <p>Own the night!</p>
      <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Party Cities
        <span class="fa fa-search"></span></button>
        <ul class="dropdown-menu dropdown-menu-background">

          <li><%= link_to "Las Vegas", clubs_path(city: 'Las Vegas') %></li>
          <li><%= link_to "New York", clubs_path(city: 'New York') %></li>
          <li><%= link_to "London", clubs_path(city: 'London') %></li>

        </ul>

      </div>

    </div>
  </div>
</div>


<!-- <div class="divider-new">Upcoming events</div>
<div class="container">
  <div class="row">
    <%# @events.each do |event| %>
    <%# @club_id = event.club_id %>
    <%# @club = Club.find(@club_id) %>
    <div class="col-xs-12 col-md-4">
      <%#= link_to event_path(event) do %>
      <div class="card small card-product hoverable">
        <div class='card-thumbnail' style="background-image: url('<%#= image_url event.photos.first.try(:photo) %>');" >
          <div class="price"><%#="Tables starts @" + event.cheapest_table + " " + "$"%></div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <h7>
              <span class="Roboto-Bold">
                <div class="starttime"><%#= event.starts_at.strftime("%-d %b") %>  <br></div>
                <div class="clubname"><%#= @club.name %> <br>
                </div>
              </span>
            </h7>
            <h7>
              <span class="Roboto-Thin">
                <div class="city"><%#= @club.city %>
                </div>
              </span>
            </h7>
          </div>
          <div class="col-xs-6">
            <%#= link_to "Host", event_path(event), class: "brand-button" %>
          </div>
        </div>
      </div>

      <#% end %>
    </div>
    <#% end %>
  </div>
</div>
 -->

<div class="divider-new">Available tables</div>


<div class="container">
  <div class="row">
    <% @tables.each_with_index do |table, index| %>
      <div class="col-xs-12 col-md-4">
        <%= render "table_card", table: table, index: index+1 %>
      </div>
    <% end %>
  </div>
</div>