config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :owners
  get 'dashboard' => 'clubs#index'
  get 'privacy' => 'pages#privacy'

  root to: 'pages#home'

  resources :clubs do
    resources :photos, only: [:create]
  end

  resources :events, :tables
  resources :bookings, only: [:create, :new, :destroy]

  get 'bookings/new/:club_id/:event_id/:table_id', to: "bookings#new", as: "facebook"

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :table, only: [:show, :edit, :destroy, :update, :host]

  def create
    table = Table.new(table_params)
    table.event_id = params[:event]
    table.available_seats = table.seats
    table.per_seat = table.price / table.seats
    table.payment_status = "Free"
    if table.save
      redirect_to table_path(table)
    else
      render :new
    end
  end

  def new
    @table = Table.new
  end

  def edit
  end

  def update
  end

  def show
    # @club = Club.find(params[:club_id])
    # @event = Event.find(params[:event_id])
  end

  def index
    @club = Club.find(params[:club_id])
    @event = Event.find(params[:event_id])
    @tables = @event.tables
  end

  def destroy
  end

  private

  def table
    @table = Table.find(params[:id])
  end

  def table_params
    params.require(:table).permit(:seats, :available_seats, :price, :per_seat,
      :payment_status, :preferences, :event_id, :user_id)
  end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/edit.html.erb
<h1>Tables#edit</h1>
<p>Find me in app/views/tables/edit.html.erb</p>

app/views/tables/host.html.erb
<div class="container text-center">
  <div class="row">

    <div class="col-xs-12 ">
    <h3>Table Hosting </h3>
      <h5> <%= @event.starts_at.strftime("%-d %b") %>  : <%= @event.description %>
             @ <%= @club.name %> - <%= @club.description %> </h5>
      </div>
    </div>
  </div>

app/views/tables/index.html.erb
      <h4 class="text-center">Table Booking </h4>
      <%= render '/shared/event' %>

  <div class="container table-responsive">
    <div class="row">
    <div class="col-md-offset-2 col-md-8">
     <table class="table table-condensed">
       <thead>
         <tr>
           <th>Seats</th>
           <th>Available</th>
           <th>Table Price</th>
           <th>Seat Price</th>
           <th>Status</th>
           <th>Host </th>
           <th colspan="2"></th>
         </tr>
       </thead>

       <tbody>
         <% @tables.each do |table| %>
         <div class="col-xs-12 col-md-4">
           <tr>
             <td>  <%= table.seats %> </td>
             <td>  <%= table.available_seats %> </td>
             <td>  €<%= table.price %> </td>
             <td>  €<%= table.per_seat %> </td>
             <td class="tabsts">  <%= table.payment_status %></td>
             <% if current_user %>
              <% if table.user_id.present? %>
                <% if table.payment_status == "Full" %>
                  <td> <%= link_to "Table Full", table_path(table) %> </td>
                <% else %>
                  <td id="bgtable"> <%= link_to "Join this Table", new_booking_path(table, club_id: @club.id, event_id: @event.id, table_id: table.id) %></td>
                <% end %>
              <% else %>
                <td id="bgtable"> <%= link_to "Host this Table", new_booking_path(table, club_id: @club.id, event_id: @event.id, table_id: table.id) %> </td>
              <% end %>
             <% else %>
              <td id="bgtable"> <%= link_to "Sign In to Join/Host", new_user_session_path %> </td>
             <% end %>
              <td>

                <% if table.user_id.present? %>
                  <%= link_to image_tag(table.user.picture, class: "avatar"), table_path(table, club_id: @club.id, event_id: @event.id) %>
              </td>
              <% end %>
            </tr>
          </div>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>

app/views/tables/new.html.erb
<div class="container">
<h1 class="text-center">New Table</h1>

<%= simple_form_for @table do |f| %>
    <%= f.input :seats %>
    <%= f.input :price %>
    <%= f.input :preferences %>
    <%= f.input :promotion %>

    <%= f.button :submit %>
  <% end %>

</div>

app/views/tables/show.html.erb
<div class="container text-center">
  <div class="row">

    <div class="col-sm-6">
      <div>
        <p> A Premium Table of <%= @table.seats %>  With <%= @table.available_seats %> Seats Available </p>
        <p>This table costs €<%= @table.price %> - or €<%= @table.per_seat %> per seat</p>
        <p>Table preferences : <%= @table.preferences %> </p>
        <p>This table is hosted by: <%= @table.user.first_name %> <%= @table.user.last_name %></p>
        <%= image_tag(@table.user.picture) %>

      </div>
    </div>

    <div class="col-sm-6">
      <h5> <em><%= @table.seats - @table.available_seats %> Bookings for this Table </em> </h5>
      <div class="text-left small">

        <% @table.bookings.order(:id).each do |booking|  %>

        <div class="row">
          <div class="col-sm-2">
            <%= image_tag(booking.user.picture,  class: "avatar-large") %>
          </div>

          <div class="col-sm-10">
           <span class="mark"> <%= booking.user.first_name %> <%= booking.user.last_name %> </span>
            Booked <%= booking.seats %> seats <br>
            Comments: <%= booking.description %>
          </div>
        </div>

        <% end %>

        <!-- Share on FB > NEEDS STYLING -->
        <a class='btn btn-facebook' href="https://www.facebook.com/sharer/sharer.php?u=<%= facebook_url(@table.event.club_id, @table.event_id, @table.id) %>"> Share the great news on <i class="fa fa-facebook-official"></i></a>


        <%# if current_user && @table.available_seats > 0 %>
          <%#= link_to "Join this Table", new_booking_path(@table, club_id: params[:club_id], event_id: params[:event_id], table_id: @table.id), class: "btn btn-default text-center" %>
        <%# end %>

      </div>
    </div>

    </div>
    </div>

app/views/tables/update.html.erb
<h1>Tables#update</h1>
<p>Find me in app/views/tables/update.html.erb</p>